### ISSUE TITLE
Native image can't run on alpine

### ISSUE THREAD

**Issue by Gaojianli** [Ghost-chu/PeerBanHelper#63]
Source: Github Release
Log:
```
[2024/04/16 05:46:30] [SEVERE ] [错误] PeerBanHelper 启动失败，遇到致命错误，请检查控制台日志 
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Error opening connection
	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:584)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:571)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:98)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:80)
	at com.ghostchu.peerbanhelper.database.DatabaseManager.setupDatabase(DatabaseManager.java:37)
	at com.ghostchu.peerbanhelper.database.DatabaseManager.<init>(DatabaseManager.java:25)
	at com.ghostchu.peerbanhelper.PeerBanHelperServer.prepareDatabase(PeerBanHelperServer.java:134)
	at com.ghostchu.peerbanhelper.PeerBanHelperServer.<init>(PeerBanHelperServer.java:97)
	at com.ghostchu.peerbanhelper.Main.main(Main.java:89)
	at java.base@22/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: java.sql.SQLException: Error opening connection
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:283)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:67)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19)
	at org.sqlite.JDBC.createConnection(JDBC.java:106)
	at org.sqlite.JDBC.connect(JDBC.java:79)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:120)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:550)
	... 8 more
Caused by: org.sqlite.NativeLibraryNotFoundException: No native library found for os.name=Linux-Musl, os.arch=x86_64, paths=[/usr/lib64:/lib64:/lib:/usr/lib]
	at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:361)
	at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:75)
	at org.sqlite.core.NativeDB.load(NativeDB.java:69)
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:280)
	... 18 more
```

**Comment by Ghost-chu** [comment]
Musl 和 ARM/RISCV 等架构目前未正式支持。

https://github.com/xerial/sqlite-jdbc/blob/master/src/main/resources/org/sqlite/native/Linux-Musl/x86_64/libsqlitejdbc.so

**Comment by Gaojianli** [comment]
> Musl 和 ARM/RISCV 等架构目前未正式支持。
> 
> https://github.com/xerial/sqlite-jdbc/blob/master/src/main/resources/org/sqlite/native/Linux-Musl/x86_64/libsqlitejdbc.so

It works, thanks 
https://github.com/Ghost-chu/PeerBanHelper/pull/64
