### ISSUE TITLE
在Windows上运行错误

### ISSUE THREAD

**Issue by HiruOcha** [Ghost-chu/PeerBanHelper#9]
用的客户端是qBittorent Enhanced Edition v4.6.3.10
在启动后报错，输出如下日志，并且qBittorent无响应
今天突然变成这样的，不知道什么原因

`[14:09:58] [main/INFO]: PeerBanHelper - v1.5 - by Ghost_chu
[14:09:58] [main/INFO]: 加载配置文件……
[14:09:58] [main/INFO]:  + qBittorrent -> my-really-good-best-ever-bittorrent-downloader (http://127.0.0.1:8080)
[14:09:58] [main/INFO]: 正在启动功能模块……
[14:09:58] [main/INFO]: [注册] IP Blacklist
[14:09:58] [main/INFO]: [注册] PeerId Blacklist
[14:09:58] [main/INFO]: [注册] ClientName Blacklist
[14:09:58] [main/INFO]: [注册] Progress Cheat Blocker
[14:10:59] [Peer check/WARN]: 在处理 my-really-good-best-ever-bittorrent-downloader (http://127.0.0.1:8080/api/v2) 的 WebAPI 操作时出现了一个非预期的错误
kong.unirest.UnirestException: java.net.SocketTimeoutException: Read timed out
	at kong.unirest.DefaultInterceptor.onFail(DefaultInterceptor.java:43) ~[PeerBanHelper.jar:?]
	at kong.unirest.CompoundInterceptor.lambda$onFail$2(CompoundInterceptor.java:54) ~[PeerBanHelper.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.Collections$2.tryAdvance(Collections.java:5073) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?]
	at kong.unirest.CompoundInterceptor.onFail(CompoundInterceptor.java:56) ~[PeerBanHelper.jar:?]
	at kong.unirest.apache.ApacheClient.request(ApacheClient.java:138) ~[PeerBanHelper.jar:?]
	at kong.unirest.Client.request(Client.java:57) ~[PeerBanHelper.jar:?]
	at kong.unirest.BaseRequest.request(BaseRequest.java:365) ~[PeerBanHelper.jar:?]
	at kong.unirest.BaseRequest.asString(BaseRequest.java:218) ~[PeerBanHelper.jar:?]
	at com.ghostchu.peerbanhelper.downloader.impl.qbittorrent.QBittorrent.getPeers(QBittorrent.java:82) ~[PeerBanHelper.jar:?]
	at com.ghostchu.peerbanhelper.PeerBanHelperServer.banDownloader(PeerBanHelperServer.java:129) ~[PeerBanHelper.jar:?]
	at com.ghostchu.peerbanhelper.PeerBanHelperServer.banWave(PeerBanHelperServer.java:83) [PeerBanHelper.jar:?]
	at com.ghostchu.peerbanhelper.PeerBanHelperServer$1.run(PeerBanHelperServer.java:69) [PeerBanHelper.jar:?]
	at java.util.TimerThread.mainLoop(Timer.java:566) [?:?]
	at java.util.TimerThread.run(Timer.java:516) [?:?]
Caused by: java.net.SocketTimeoutException: Read timed out
	at sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:278) ~[?:?]
	at sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:304) ~[?:?]
	at sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346) ~[?:?]
	at sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796) ~[?:?]
	at java.net.Socket$SocketInputStream.read(Socket.java:1109) ~[?:?]
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137) ~[PeerBanHelper.jar:?]
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153) ~[PeerBanHelper.jar:?]
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280) ~[PeerBanHelper.jar:?]
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138) ~[PeerBanHelper.jar:?]
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56) ~[PeerBanHelper.jar:?]
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259) ~[PeerBanHelper.jar:?]
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163) ~[PeerBanHelper.jar:?]
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157) ~[PeerBanHelper.jar:?]
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273) ~[PeerBanHelper.jar:?]
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125) ~[PeerBanHelper.jar:?]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272) ~[PeerBanHelper.jar:?]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[PeerBanHelper.jar:?]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[PeerBanHelper.jar:?]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[PeerBanHelper.jar:?]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[PeerBanHelper.jar:?]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:118) ~[PeerBanHelper.jar:?]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[PeerBanHelper.jar:?]
	at kong.unirest.apache.ApacheClient.request(ApacheClient.java:129) ~[PeerBanHelper.jar:?]
	... 9 more
`

**Comment by HiruOcha** [comment]
没毛病啊
![image](https://github.com/Ghost-chu/PeerBanHelper/assets/86976382/9a38413a-3138-4d52-b0e6-4cefcb727670)
![image](https://github.com/Ghost-chu/PeerBanHelper/assets/86976382/beb011c2-de87-4ffe-80ab-173a11018bb6)
今天早上都还能用的，重启一下就不行了

**Comment by Ghost-chu** [comment]
192.168.0.4 是你路由器分配的设备IP吧，你得固定住 IP 不能让它变。如果qb和PBH在一台机器上，就用127.0.0.1。

程序本身没问题的，最近没有新的更新。要么一直能用要么一直不能用。

**Comment by HiruOcha** [comment]
127.0.0.1也试过，一样的报错，我再去研究一下吧

**Comment by HiruOcha** [comment]
噢，突然间又能用了
